<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Hayes_Hunter-Selesitino</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Hayes_Hunter-Selesitino_files/libs/clipboard/clipboard.min.js"></script>
<script src="Hayes_Hunter-Selesitino_files/libs/quarto-html/quarto.js"></script>
<script src="Hayes_Hunter-Selesitino_files/libs/quarto-html/popper.min.js"></script>
<script src="Hayes_Hunter-Selesitino_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Hayes_Hunter-Selesitino_files/libs/quarto-html/anchor.min.js"></script>
<link href="Hayes_Hunter-Selesitino_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Hayes_Hunter-Selesitino_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Hayes_Hunter-Selesitino_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Hayes_Hunter-Selesitino_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Hayes_Hunter-Selesitino_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Hayes_Hunter-Selesitino</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(brms) <span class="co"># for statistics</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Rcpp</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading 'brms' package (version 2.23.0). Useful instructions
can be found by typing help('brms'). A more detailed introduction
to the package is available through vignette('brms_overview').</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'brms'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    ar</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects) <span class="co"># for the prediction plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggeffects' was built under R version 4.5.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lterdatasampler) <span class="co"># for built-in datasets</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pie_crab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  date       latitude site   size air_temp air_temp_sd water_temp water_temp_sd
  &lt;date&gt;        &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;
1 2016-07-24       30 GTM    12.4     21.8        6.39       24.5          6.12
2 2016-07-24       30 GTM    14.2     21.8        6.39       24.5          6.12
3 2016-07-24       30 GTM    14.5     21.8        6.39       24.5          6.12
4 2016-07-24       30 GTM    12.9     21.8        6.39       24.5          6.12
5 2016-07-24       30 GTM    12.4     21.8        6.39       24.5          6.12
6 2016-07-24       30 GTM    13.0     21.8        6.39       24.5          6.12
# ℹ 1 more variable: name &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>pie_crab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 392 × 9
   date       latitude site   size air_temp air_temp_sd water_temp water_temp_sd
   &lt;date&gt;        &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;
 1 2016-07-24       30 GTM    12.4     21.8        6.39       24.5          6.12
 2 2016-07-24       30 GTM    14.2     21.8        6.39       24.5          6.12
 3 2016-07-24       30 GTM    14.5     21.8        6.39       24.5          6.12
 4 2016-07-24       30 GTM    12.9     21.8        6.39       24.5          6.12
 5 2016-07-24       30 GTM    12.4     21.8        6.39       24.5          6.12
 6 2016-07-24       30 GTM    13.0     21.8        6.39       24.5          6.12
 7 2016-07-24       30 GTM    10.3     21.8        6.39       24.5          6.12
 8 2016-07-24       30 GTM    11.2     21.8        6.39       24.5          6.12
 9 2016-07-24       30 GTM    12.7     21.8        6.39       24.5          6.12
10 2016-07-24       30 GTM    14.6     21.8        6.39       24.5          6.12
# ℹ 382 more rows
# ℹ 1 more variable: name &lt;chr&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Loading ggplot package and lopading library</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>pie_crab <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> latitude, <span class="at">y =</span> size)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Make the y-axis include 0</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="cn">NA</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hayes_Hunter-Selesitino_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="q1.1" class="level4">
<h4 class="anchored" data-anchor-id="q1.1">Q1.1</h4>
<p>Yes there does appear to be a linear positive trend where as latitude increase size does as well. There seems to be a lot of variation, but does follow a gradual increase. We do not feel very confident, but we do believe there is a trend, but whether it is significant we are not entirely sure.</p>
</section>
<section id="q1.2" class="level4">
<h4 class="anchored" data-anchor-id="q1.2">Q1.2</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>pie_crab <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> latitude, <span class="at">y =</span> size, <span class="at">color =</span> air_temp)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Make the y-axis include 0</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Latitude"</span>, <span class="at">y =</span> <span class="st">"Size (mm)"</span>, <span class="at">color =</span> <span class="st">"Air Temperature (C)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hayes_Hunter-Selesitino_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<p>Now that you’ve spent some time pondering the data, let’s put together our first model. From lecture, linear models follow the equation:</p>
<p><span class="math inline">\(y = intercept + slope*x\)</span></p>
<p>Let’s set up our model to look like:</p>
<p><span class="math inline">\(size = intercept + slope*latitude\)</span></p>
<hr>
</section>
<section id="fit-linear-regression-with-brms" class="level2">
<h2 class="anchored" data-anchor-id="fit-linear-regression-with-brms">1.2 Fit linear regression with <code>brms</code></h2>
<hr>
<p>Time to run the model! We will be using the <code>brm()</code> function. There’s a lot here, so let’s dig in line-by-line:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># latitude model</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>m.crab.lat <span class="ot">&lt;-</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">brm</span>(<span class="at">data =</span> pie_crab, <span class="co"># Give the model the pie_crab data</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Choose a gaussian (normal) distribution</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> gaussian,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Specify the model here. </span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>      size <span class="sc">~</span> latitude,</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Here's where you specify parameters for executing the Markov chains</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>      <span class="co"># We're using similar to the defaults, except we set cores to 4 so the analysis runs faster than the default of 1</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">iter =</span> <span class="dv">2000</span>, <span class="at">warmup =</span> <span class="dv">1000</span>, <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">cores =</span> <span class="dv">4</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Setting the "seed" determines which random numbers will get sampled.</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>      <span class="co"># In this case, it makes the randomness of the Markov chain runs reproducible </span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>      <span class="co"># (so that both of us get the exact same results when running the model)</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">seed =</span> <span class="dv">4</span>,</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Save the fitted model object as output - helpful for reloading in the output later</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">file =</span> <span class="st">"output/m.crab.lat"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="q1.3-what-does-the-iter-argument-do" class="level3">
<h3 class="anchored" data-anchor-id="q1.3-what-does-the-iter-argument-do">Q1.3 What does the “iter” argument do?</h3>
</section>
<section id="q1.3-the-iter-argument-specifies-how-many-time-the-model-will-sample-the-posterier-distribution.in-other-words-the-total-number-of-iterations-per-chain." class="level3">
<h3 class="anchored" data-anchor-id="q1.3-the-iter-argument-specifies-how-many-time-the-model-will-sample-the-posterier-distribution.in-other-words-the-total-number-of-iterations-per-chain.">Q1.3: The iter argument specifies how many time the model will sample the posterier distribution.In other words the total number of iterations per chain.</h3>
<p>Navigate to the <code>brm</code> help page to answer: What does the <code>iter =</code> argument do?</p>
<hr>
</section>
</section>
<section id="assess-model" class="level2">
<h2 class="anchored" data-anchor-id="assess-model">1.3 Assess model</h2>
<p>First, we need to assess whether or not our model actually ran correctly. Let’s print a summary of the model output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m.crab.lat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: gaussian 
  Links: mu = identity 
Formula: size ~ latitude 
   Data: pie_crab (Number of observations: 392) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Regression Coefficients:
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept    -3.61      1.30    -6.09    -1.01 1.00     4116     3192
latitude      0.48      0.03     0.42     0.55 1.00     4108     3140

Further Distributional Parameters:
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma     2.84      0.10     2.65     3.04 1.00     3758     2852

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<p>We do this in part by looking at the <code>Rhat</code> (R hat) column, which should be very close to 1. If you remember from lecture, this model runs multiple chains that converge on estimates for the slope and the intercept. An R hat of 1 tells us that those four chains converged on the same estimate. This looks fine for us!</p>
<p>Let’s also look at the chains and the “posterior distributions” in a graph.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m.crab.lat) <span class="co"># show posteriors and chains</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hayes_Hunter-Selesitino_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We’re looking for three things:</p>
<ol type="1">
<li>Are the posterior samples on the left each a smooth distribution, with one clean peak, or do they have multiple clear peaks? The latter is a bad sign. They look good in this case.</li>
<li>Are the four chains on the overlapping each other, or are they clearly separate? The latter is a bad sign. We again look good in this case.</li>
<li>Are the four chains flat, or is there a clear trend up or down? The latter is a bad sign. We again look good in this case.</li>
</ol>
<p>If we fail any of these tests, we would want to try running the MCMC chain with more iterations. We may also need to think hard about whether our model is correctly designed.</p>
<hr>
</section>
<section id="interpret-model" class="level2">
<h2 class="anchored" data-anchor-id="interpret-model">1.4 Interpret model</h2>
<p>Now that we feel good that the model fit correctly, let’s look at a summary table of our model’s output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m.crab.lat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: gaussian 
  Links: mu = identity 
Formula: size ~ latitude 
   Data: pie_crab (Number of observations: 392) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Regression Coefficients:
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept    -3.61      1.30    -6.09    -1.01 1.00     4116     3192
latitude      0.48      0.03     0.42     0.55 1.00     4108     3140

Further Distributional Parameters:
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma     2.84      0.10     2.65     3.04 1.00     3758     2852

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<p>The output reminds us of our model formula that we chose (<code>size ~ latitude</code>). Most important to answering our question are the parameter estimates in the <code>estimate</code> column. Remember, our model was <span class="math inline">\(size = intercept + slope*latitude\)</span>. The <code>slope</code> parameter is going to tell us what the effect of latitude is. For every one unit change of latitude, what is the effect on size? We need to translate that interpretation to the units that those variables represent: the slope value is thus <em>for every one degree of latitude, carapace size changes this much in millimeters</em>.</p>
<p>Looking at our table, we see the estimate for <code>latitude</code> is 0.48: This indicates that the model estimated that for every 1 degree latitude, carapace width increases by 0.48 mm.</p>
<hr>
<p>Earlier you were asked to “<em>describe how confident you are in this interpretation</em>” when qualitatively interpreting the graph of <code>size</code> vs <code>latitude</code>. Now, let’s answer this quantitatively by examining how much confidence the model has in the size-latitude association. Are only positive (non-zero) slopes compatible with the data? Or would a flat (slope of zero) association also be compatible? If a slope of zero is compatible with the data, then we can’t really say that our predictor (latitude) has any effect on our response (size).</p>
<p>To assess this, we can look at the lower and upper 95% Credible Interval columns (<code>l-95% CI</code> and <code>u-95% CI</code>, respectively) and see if that interval range intersects with zero. We can see that our slope estimate (the estimate of <code>latitude</code>) ranges from 0.42 to 0.55 - zero is not included in this range. Therefore, we can reasonably conclude here that, given our model, the effect of latitude on body size has a 95% chance of being between those values, and importantly, NOT zero!</p>
<hr>
<p>In the results section of a paper, we would write something along these lines:</p>
<p><em>We found that crab size increased with latitude, with an increase of 0.48mm of carapace width per 1 degree of latitude. Our 95% credible intervals were between 0.42 and 0.55 mm/degree, suggesting that given our model, the effect of latitude on carapace width is different from zero.</em></p>
<hr>
<section id="bonus" class="level3">
<h3 class="anchored" data-anchor-id="bonus">Bonus</h3>
<p>Let’s calculate the probability of a zero slope! The MCMC chains are big columns of samples from the posterior distribution, so we can add up the proportion of slope estimates that are zero or lower.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as_draws_df</span>(m.crab.lat)  <span class="sc">%&gt;%</span>  <span class="co"># extract the posterior samples from the model estimate</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(b_latitude)  <span class="sc">%&gt;%</span>  <span class="co"># pull out the latitude samples from all 4 chains. we'll get a warning that we can ignore.</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">p_slope_lessthanorequalto_zero =</span> <span class="fu">sum</span>(b_latitude <span class="sc">&lt;=</span> <span class="dv">0</span>)<span class="sc">/</span><span class="fu">length</span>(b_latitude))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Dropping 'draws_df' class as required metadata was removed.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_slope_lessthanorequalto_zero
                           &lt;dbl&gt;
1                              0</code></pre>
</div>
</div>
<p>Ok! The model reports a zero chance of a slope less than or equal to zero. Feel free to try other thresholds to explore (e.g., what’s the probability the slope is greater than 0.5 mm per degree latitude?).</p>
<hr>
</section>
</section>
<section id="plot-model-on-the-data" class="level2">
<h2 class="anchored" data-anchor-id="plot-model-on-the-data">1.5 Plot model on the data</h2>
<p>Here we are going to plot the data and the model output in two different ways:</p>
<ul>
<li><pre><code>**Compatibility interval** shows uncertainty in the average response (the estimate for the slope) </code></pre></li>
<li><pre><code>**Prediction interval** shows uncertainty in the data around the average response (the estimate for the slope)</code></pre></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compatibility interval. the shows uncertainty in the average response.</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>confm.crab.lat <span class="ot">&lt;-</span> <span class="fu">predict_response</span>(m.crab.lat)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(confm.crab.lat, <span class="at">show_data =</span> <span class="cn">TRUE</span>) <span class="co"># shows variation in the average.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Data points may overlap. Use the `jitter` argument to add some amount of
  random variation to the location of data points and avoid overplotting.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hayes_Hunter-Selesitino_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prediction interval. this shows uncertainty in the data around the average response.</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>confm.crab.lat <span class="ot">&lt;-</span> <span class="fu">predict_response</span>(m.crab.lat, <span class="at">interval =</span> <span class="st">'prediction'</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(confm.crab.lat, <span class="at">show_data =</span> <span class="cn">TRUE</span>) <span class="co"># shows 95% confidence interval of points</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Data points may overlap. Use the `jitter` argument to add some amount of
  random variation to the location of data points and avoid overplotting.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hayes_Hunter-Selesitino_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="repeat-with-a-new-variable-water-temp-sd" class="level2">
<h2 class="anchored" data-anchor-id="repeat-with-a-new-variable-water-temp-sd">1.6 Repeat with a new variable: water temp sd</h2>
<p>Let’s repeat this example with a new variable: the water temperature standard deviation, <code>water_temp_sd</code>. The standard deviation (sd) can be used as a metric of variability: higher sd means higher variability. We can ask: <em>is higher variability in water temperature associated with fiddler crab body size?</em></p>
<hr>
<section id="q1.4-make-a-hypothesis" class="level3">
<h3 class="anchored" data-anchor-id="q1.4-make-a-hypothesis">Q1.4 Make a hypothesis</h3>
<p><em>Before</em> you look at the data, what direction of an effect do you expect? Do you think higher variability would be associated with larger or smaller crabs? Why? Please write 1-2 sentences.</p>
<section id="q1.4" class="level4">
<h4 class="anchored" data-anchor-id="q1.4">Q1.4:</h4>
<p>We predict that higher variability would be associated with larger crabs. Because generally we see larger species of crab in colder environments that experience more disturbance.</p>
<hr>
</section>
</section>
<section id="q1.5-graph-the-data" class="level3">
<h3 class="anchored" data-anchor-id="q1.5-graph-the-data">Q1.5 Graph the data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>pie_crab <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> water_temp_sd, <span class="at">y =</span> size, <span class="at">color =</span> water_temp)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Make the y-axis include 0</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Water Temperature SD"</span>, <span class="at">y =</span> <span class="st">"Fiddler Crab Boddy Size(mm)"</span>, <span class="at">color =</span> <span class="st">"Water Temperature(C)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hayes_Hunter-Selesitino_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="q1.6-interpret-the-graph" class="level3">
<h3 class="anchored" data-anchor-id="q1.6-interpret-the-graph">Q1.6 Interpret the graph</h3>
<p>Does it look like size changes with the sd of water temperature? Describe how confident you are in this interpretation.</p>
<section id="q1.6" class="level4">
<h4 class="anchored" data-anchor-id="q1.6">Q1.6:</h4>
<p>No, it does not look like size changes with standard deviation of water temperature. I feel very confident that there’s not pattern to distinguish amongst the data.</p>
<hr>
</section>
</section>
<section id="q1.7-set-up-and-run-this-new-model" class="level3">
<h3 class="anchored" data-anchor-id="q1.7-set-up-and-run-this-new-model">Q1.7 Set up and run this new model</h3>
<p>We’ll set up our model to look like:</p>
<p><span class="math inline">\(size = intercept + slope*watertempsd\)</span></p>
<hr>
<p>Keep all of the output the same except for the parts where you specify 1) the model formula and 2) the <code>file =</code> output. Name this new model <code>m.crab.watersd</code> to distinguish it from the latitude model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># latitude model</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>m.crab.watersd <span class="ot">&lt;-</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">brm</span>(<span class="at">data =</span> pie_crab, <span class="co"># Give the model the pie_crab data</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Choose a gaussian (normal) distribution</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> gaussian,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Specify the model here. </span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>      size <span class="sc">~</span> water_temp_sd,</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Here's where you specify parameters for executing the Markov chains</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>      <span class="co"># We're using similar to the defaults, except we set cores to 4 so the analysis runs faster than the default of 1</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">iter =</span> <span class="dv">2000</span>, <span class="at">warmup =</span> <span class="dv">1000</span>, <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">cores =</span> <span class="dv">4</span>,</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Setting the "seed" determines which random numbers will get sampled.</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>      <span class="co"># In this case, it makes the randomness of the Markov chain runs reproducible </span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>      <span class="co"># (so that both of us get the exact same results when running the model)</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">seed =</span> <span class="dv">4</span>,</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Save the fitted model object as output - helpful for reloading in the output later</span></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">file =</span> <span class="st">"output/m.crab.watersd"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
<section id="q1.8-assess-the-model" class="level3">
<h3 class="anchored" data-anchor-id="q1.8-assess-the-model">Q1.8 Assess the model</h3>
<p>Assess whether the model ran correctly by looking at R hat, the chains, and the posterior distributions using the plot() and summary() functions as below. Describe your thought process about whether the model ran correctly in 1-2 sentences.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show posteriors and chains</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m.crab.watersd) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hayes_Hunter-Selesitino_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show summary, including rhat</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m.crab.watersd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: gaussian 
  Links: mu = identity 
Formula: size ~ water_temp_sd 
   Data: pie_crab (Number of observations: 392) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Regression Coefficients:
              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept        13.95      1.21    11.54    16.36 1.00     4569     2971
water_temp_sd     0.10      0.16    -0.23     0.42 1.00     4615     2950

Further Distributional Parameters:
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma     3.52      0.13     3.28     3.76 1.00     3960     2894

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<section id="q1.8" class="level4">
<h4 class="anchored" data-anchor-id="q1.8">Q1.8:</h4>
<p>Since the Rhat value is equal to 1 and all of the chains (1-4) line up in a straight line across the graph, we feel confident that the model ran correctly.</p>
<hr>
</section>
</section>
<section id="q1.9-interpret-the-model" class="level3">
<h3 class="anchored" data-anchor-id="q1.9-interpret-the-model">Q1.9 Interpret the model</h3>
<p>Based on the summary output, interpret your model by answering:</p>
<ol type="1">
<li>What is the effect of your predictor? This information is in the <code>estimate</code> column to the right of your predictor <code>water_temp_sd</code>. Remember to describe the effect using the units to make it biologically meaningful.</li>
<li>Is the effect reasonably different from zero? In other words, does the confidence interval intersect with zero?</li>
</ol>
<section id="q1.9" class="level4">
<h4 class="anchored" data-anchor-id="q1.9">Q1.9</h4>
</section>
<section id="q1.9-1" class="level4">
<h4 class="anchored" data-anchor-id="q1.9-1">Q1.9:</h4>
<ol type="1">
<li><p>The effect of the predictor variable is 0.10, meaning for every one unit of water temperature standard deviation, there was an increase of 0.10mm in fiddler crab body size.</p></li>
<li><p>No, the effect is not reasonably different from zero because the credible interval (-0.23 - 0.42) intersects with zero. Therefore this tells us that given the model, there is a possibility that the predictor ( standard deviation of water temperature) could have no effect on fiddler crab body size.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show model output</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m.crab.watersd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p>This is a situation where our predictor variable, <code>water_temp_sd</code>, does not seem to have an effect on the body size of crabs. We would say something along the lines of: <em>We found an increase of 0.10mm of carapace width per 1 unit of the standard deviation of water temperature, but our 95% credible intervals included zero (-0.20 to 0.40), suggesting that given our model, the effect of water temperature standard deviation on carapace width is not different from zero.</em></p>
<hr>
</section>
</section>
</section>
<section id="back-to-pikas" class="level1">
<h1>2. Back to Pikas!</h1>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="adultPikaNiwotRidge_SaraMcLaughlin.jpeg" class="img-fluid figure-img"></p>
<figcaption>adultPikaNiwotRidge_SaraMcLaughlin</figcaption>
</figure>
</div>
<p>We can’t stay away from the cute pikas for too long! In this section you will apply the statistical thinking you’ve learned to the pika dataset in one of two ways: you will try and see whether or not the stress of pikas is explained by either 1) elevation or 2) day of year.</p>
<p>Let’s look at the data again</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nwt_pikas)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  date       site      station utm_easting utm_northing sex   concentration_pg_g
  &lt;date&gt;     &lt;fct&gt;     &lt;fct&gt;         &lt;dbl&gt;        &lt;dbl&gt; &lt;fct&gt;              &lt;dbl&gt;
1 2018-06-08 Cable Ga… Cable …      451373      4432963 male              11563.
2 2018-06-08 Cable Ga… Cable …      451411      4432985 male              10629.
3 2018-06-08 Cable Ga… Cable …      451462      4432991 male              10924.
4 2018-06-13 West Kno… West K…      449317      4434093 male              10414.
5 2018-06-13 West Kno… West K…      449342      4434141 male              13531.
6 2018-06-13 West Kno… West K…      449323      4434273 &lt;NA&gt;               7799.
# ℹ 1 more variable: elev_m &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Date is one of the columns, but we specifically want “day of year” as a metric to quantify how late in the season it is. This also allows us to interpret our model’s output a little more informatively.</p>
<p>We can extract day of year using the <code>lubridate</code> package (within <code>tidyverse</code>), which is all about working with dates and times:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting Day from the date and makint it its own column.</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>nwt_pikas_doy <span class="ot">&lt;-</span> nwt_pikas <span class="sc">%&gt;%</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add a new column called day_of_year</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># yday extracts the day of year from the date column</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">day_of_year =</span> <span class="fu">yday</span>(date)) <span class="sc">%&gt;%</span> </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># relocate the day_of_year column after the date column</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(day_of_year, <span class="at">.after =</span> date)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nwt_pikas_doy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  date       day_of_year site       station      utm_easting utm_northing sex  
  &lt;date&gt;           &lt;dbl&gt; &lt;fct&gt;      &lt;fct&gt;              &lt;dbl&gt;        &lt;dbl&gt; &lt;fct&gt;
1 2018-06-08         159 Cable Gate Cable Gate 1      451373      4432963 male 
2 2018-06-08         159 Cable Gate Cable Gate 2      451411      4432985 male 
3 2018-06-08         159 Cable Gate Cable Gate 3      451462      4432991 male 
4 2018-06-13         164 West Knoll West Knoll 3      449317      4434093 male 
5 2018-06-13         164 West Knoll West Knoll 4      449342      4434141 male 
6 2018-06-13         164 West Knoll West Knoll 5      449323      4434273 &lt;NA&gt; 
# ℹ 2 more variables: concentration_pg_g &lt;dbl&gt;, elev_m &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidying the data set further in order to create a graph we can use to visualize any kind of pattern.</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>nwt_pikas_categ <span class="ot">&lt;-</span> nwt_pikas <span class="sc">%&gt;%</span> <span class="co"># naming output of this code</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Call the new column stress_category</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">stress_category =</span> <span class="fu">case_when</span>(</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="co"># When the value is &gt; 5000, make the new column's value "Stressed!!!!"</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>concentration_pg_g <span class="sc">&gt;</span> <span class="dv">5000</span> <span class="sc">~</span> <span class="st">"Stressed"</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Otherwise, make the new column's value "Chill"</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="at">.default =</span> <span class="st">"Chill"</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now it’s time to choose! In this section, <strong>choose between explaining the stress variable as a function of either <code>day of year</code> or <code>elevation</code></strong>. If you have extra time at the end and would like more practice, you may optionally repeat the analysis on the other variable as well.</p>
<hr>
<section id="q2.1-make-a-question" class="level3">
<h3 class="anchored" data-anchor-id="q2.1-make-a-question">Q2.1 Make a question</h3>
<p>Clearly articulate the question that you want to ask in one sentence.</p>
<section id="q2.1" class="level4">
<h4 class="anchored" data-anchor-id="q2.1">Q2.1:</h4>
<p>Is the variation in elevations associated with the stress of pikas?</p>
<hr>
</section>
</section>
<section id="q2.2-make-a-hypothesis" class="level3">
<h3 class="anchored" data-anchor-id="q2.2-make-a-hypothesis">Q2.2 Make a hypothesis</h3>
<p><em>Before</em> you look at the data, what direction of an effect do you expect? Do you think a larger value of the predictor you chose would be associated with more or less stressed pikas? Why? Please write 1-2 sentences.</p>
<section id="q2.2" class="level4">
<h4 class="anchored" data-anchor-id="q2.2">Q2.2:</h4>
<p>We predict that higher elevations will be associated with higher stress levels in pika. Because generally, the environment at higher elevations are more unforgiving due to limited resource availability, such as plants which is the pikas main source of food, because not many plants are able to survive at such high elevations, as well as more limited land resources, so there are fewer viable territories available for pikas to choose from, leading to more conflict amongst individuals.</p>
<hr>
</section>
</section>
<section id="q2.3-graph-the-data" class="level3">
<h3 class="anchored" data-anchor-id="q2.3-graph-the-data">Q2.3 Graph the data</h3>
<p>As before, your response variable (stress, which is measured as <code>concentration_pg_g</code>) should be on the y-axis, with your predictor variable on the x.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nwt_pikas_categ) <span class="co"># checking column names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  date       site      station utm_easting utm_northing sex   concentration_pg_g
  &lt;date&gt;     &lt;fct&gt;     &lt;fct&gt;         &lt;dbl&gt;        &lt;dbl&gt; &lt;fct&gt;              &lt;dbl&gt;
1 2018-06-08 Cable Ga… Cable …      451373      4432963 male              11563.
2 2018-06-08 Cable Ga… Cable …      451411      4432985 male              10629.
3 2018-06-08 Cable Ga… Cable …      451462      4432991 male              10924.
4 2018-06-13 West Kno… West K…      449317      4434093 male              10414.
5 2018-06-13 West Kno… West K…      449342      4434141 male              13531.
6 2018-06-13 West Kno… West K…      449323      4434273 &lt;NA&gt;               7799.
# ℹ 2 more variables: elev_m &lt;dbl&gt;, stress_category &lt;chr&gt;</code></pre>
</div>
</div>
<section id="q2.3" class="level4">
<h4 class="anchored" data-anchor-id="q2.3">Q2.3:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>pika_stress_Plot1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nwt_pikas_categ, <span class="fu">aes</span>(<span class="at">x =</span> elev_m, <span class="at">y =</span> concentration_pg_g, <span class="at">color =</span> )) <span class="sc">+</span> </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>elev_m)) <span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Make the y-axis include 0</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Elevation (m)"</span>, <span class="at">y =</span> <span class="st">"Conc. of Glucocorticoid Metabolite (GCM/gram)"</span>, <span class="at">color =</span> <span class="st">"Elevation (m)"</span>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>pika_stress_Plot1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hayes_Hunter-Selesitino_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<p><em>We found an increase of 0.10mm of carapace width per 1 unit of the standard deviation of water temperature, but our 95% credible intervals included zero (-0.20 to 0.40), suggesting that given our model, the effect of water temperature standard deviation on carapace width is not different from zero.</em></p>
</section>
</section>
<section id="q2.4-set-up-and-run-a-model" class="level3">
<h3 class="anchored" data-anchor-id="q2.4-set-up-and-run-a-model">Q2.4 Set up and run a model</h3>
<p>Make sure you store your model output as something informative to you.</p>
<section id="q2.4" class="level4">
<h4 class="anchored" data-anchor-id="q2.4">Q2.4:</h4>
<p>We stored output in a new dataframe called “nwt_pika_elev_stress.”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Elevation and pika stress model </span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>nwt_pikas_elev_stress <span class="ot">&lt;-</span> </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">brm</span>(<span class="at">data =</span> nwt_pikas_categ, <span class="co"># Give the model tidied pika data.frame</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Chose a gaussian (normal) distribution</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> gaussian,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Specified model. </span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>      concentration_pg_g <span class="sc">~</span> elev_m,</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Here's where you specify parameters for executing the Markov chains</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>      <span class="co"># We're using similar to the defaults, except we set cores to 4 so the analysis runs faster than the default of 1</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">iter =</span> <span class="dv">2000</span>, <span class="at">warmup =</span> <span class="dv">1000</span>, <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">cores =</span> <span class="dv">4</span>,</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Setting the "seed" determines which random numbers will get sampled.</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>      <span class="co"># In this case, it makes the randomness of the Markov chain runs reproducible </span></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>      <span class="co"># (so that both of us get the exact same results when running the model)</span></span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">seed =</span> <span class="dv">4</span>,</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Save the fitted model object as output - helpful for reloading in the output later</span></span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">file =</span> <span class="st">"output/nwt_pikas_elev_stress"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p><em>We found an increase of 0.10mm of carapace width per 1 unit of the standard deviation of water temperature, but our 95% credible intervals included zero (-0.20 to 0.40), suggesting that given our model, the effect of water temperature standard deviation on carapace width is not different from zero.</em></p>
</section>
</section>
<section id="q2.5-assess-the-model" class="level3">
<h3 class="anchored" data-anchor-id="q2.5-assess-the-model">Q2.5 Assess the model</h3>
<p>Assess whether the model ran correctly by looking at R hat, the chains, and the posterior distributions. Describe your thought process about whether the model ran correctly in 1-2 sentences.</p>
<section id="q2.5" class="level4">
<h4 class="anchored" data-anchor-id="q2.5">Q2.5:</h4>
<p>We are confident that our model ran correctly because our Rhat value was equal to 1, and the 4 chains all lined up with eachother and ran in a horizontal line across the graph.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show posteriors and 4 chains </span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nwt_pikas_elev_stress) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hayes_Hunter-Selesitino_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show summary, including Rhat</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nwt_pikas_elev_stress)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: gaussian 
  Links: mu = identity 
Formula: concentration_pg_g ~ elev_m 
   Data: nwt_pikas_categ (Number of observations: 109) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Regression Coefficients:
          Estimate Est.Error  l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept  6274.92   8927.98 -11361.19 23720.60 1.00     3832     2607
elev_m       -0.31      2.53     -5.25     4.69 1.00     3830     2635

Further Distributional Parameters:
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma  3011.79    209.67  2641.09  3445.75 1.00     4000     2896

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<hr>
</section>
</section>
<section id="q2.6-interpret-the-model" class="level3">
<h3 class="anchored" data-anchor-id="q2.6-interpret-the-model">Q2.6 Interpret the model</h3>
<p>Interpret your model by answering:</p>
<ol type="1">
<li>What is the effect of your predictor? Remember to describe the effect using the units to make it biologically meaningful.</li>
<li>Is the effect reasonably different from zero? How do you know?</li>
</ol>
<section id="q2.6" class="level4">
<h4 class="anchored" data-anchor-id="q2.6">Q2.6:</h4>
<p>We found that there is a decrease of 0.31 GCM/gram of Glucocorticoid Metabolite per unit of elevation. However, our 95% credible intervals (-5.25 to 4.69) includes zero. Therefore given the model, it is possible that the effects of elevation(m) on the stress levels of pika is 0.</p>
<hr>
</section>
</section>
<section id="q2.7-plot-the-model-on-the-data" class="level3">
<h3 class="anchored" data-anchor-id="q2.7-plot-the-model-on-the-data">Q2.7 Plot the model on the data</h3>
<p>Plot either a compatibility interval or prediction interval on the data; specify which you are using.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compatibility interval for pika stress and elevation. Shows uncertainty in the average response.</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>confm.pikas.elev.stress <span class="ot">&lt;-</span> <span class="fu">predict_response</span>(nwt_pikas_elev_stress)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(confm.pikas.elev.stress, <span class="at">show_data =</span> <span class="cn">TRUE</span>) <span class="co"># shows variation in the average.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Data points may overlap. Use the `jitter` argument to add some amount of
  random variation to the location of data points and avoid overplotting.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hayes_Hunter-Selesitino_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="q2.8-write-a-small-results-paragraph" class="level3">
<h3 class="anchored" data-anchor-id="q2.8-write-a-small-results-paragraph">Q2.8 Write a small results paragraph</h3>
<p>Including the information from Q2.6, write 2-3 sentences as if you were writing the results section of a scientific paper. Include a conclusion sentence that summarizes your finding.</p>
<section id="q2.8" class="level4">
<h4 class="anchored" data-anchor-id="q2.8">Q2.8:</h4>
<p>Despite the estimate showing a decrease of 0.31 GCM/grams of Glucocorticoid Metabolite in pika fecal samplers per unit of elevation. With the 95% credible interval (-5.25 to 4.69) containing 0 within its bounds it is possible that the effects of elevation(m) on the stress levels of pika is 0. Furthermore, the results of the compatibility interval shows more variation in Glucocorticoid Metabolite levels in lower elevations compared to higher ones, yet the overall mean trend is a linear horizontal line, indicating no correlation. In conclusion elevation appears to have no effect on pika stress levels.</p>
<hr>
</section>
</section>
<section id="bonus-repeat-with-the-other-variable-for-practice" class="level3">
<h3 class="anchored" data-anchor-id="bonus-repeat-with-the-other-variable-for-practice">Bonus: Repeat with the other variable for practice</h3>
<p>If you have extra time and would like more practice, you may optionally repeat these analyses with the other predictor variable.</p>
<hr>
<p>Throughout this activity, both datasets had multiple possible predictor variables that we chose between to model our response variable of interest: crab body size had latitude, temperature, and the variability of temperature. Pika stress had elevation and day of year. You may be wondering: why do we have to choose only one variable? Is it possible that both variables are important in their own way?</p>
<p>This is a great question, and is the foundation for what we will do next week, which is <em>multiple regression</em>: a way of setting up models while incorporating the influence of multiple predictors <em>at the same time</em>!</p>
<hr>
</section>
<section id="render-to-pdf" class="level3">
<h3 class="anchored" data-anchor-id="render-to-pdf">Render to PDF</h3>
<p>When you have finished, practice the GitHub push/pull:</p>
<ul>
<li>Pull to check for updates to the remote branch</li>
<li>Stage your edits (after saving your document!) by checking the documents you’d like to push</li>
<li>Commit your changes with a commit message</li>
<li>Push your changes to the remote branch</li>
</ul>
<p>And submit the well-labeled PDF on Gradescope. Thanks!</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>